### ISSUE TITLE
Example ERA5 data

### ISSUE THREAD

**Issue by crp94** [MarcCoru/locationencoder#4]
Hi!

I am very interested in this great work, particularly for encoding ERA5 and other climate data. Could you provide the dataset or a sample data file so that we could use the code era5dataset.py ?

It would be very helpful.

Thank you so much in advance!

**Comment by MarcCoru** [comment]
Hi Carlos, 

thanks for reaching out. We created the ERA 5 dataset with the following notebook 
https://github.com/MarcCoru/locationencoder/blob/main/notebooks/create_era5.ipynb

running that notebook should reproduce the data we used in the experiments.

best,
Marc

**Comment by crp94** [comment]
Thanks! This is exactly what I needed.

Best,
