### ISSUE TITLE
val_logits.npy file?

### ISSUE THREAD

**Issue by Shiran-Yuan** [MarcCoru/locationencoder#6]
Hello! Thank you for the awesome work! I noticed while trying to reproduce your results on iNat2018 that on `line 293` of `data/inat2018_loader.py` the file `val_logits.npy` was referenced, but have no idea where to find it. Could you please kindly instruct me as to how to generate or where to find this file? Thank you very much in advance for your help.

**Comment by zbirobin** [comment]
Hello! It’s great to hear that you’re attempting to reproduce our results! The `val_logits.npy` file is used to save time by avoiding the need to run the image classifier each time. You can download the file [here](https://drive.google.com/file/d/1fqf2yhGSlKj0J3_Sioku4ukGY-DMNXex/view?usp=sharing). [](https://drive.google.com/file/d/1fqf2yhGSlKj0J3_Sioku4ukGY-DMNXex/view?usp=sharing)

**Comment by Shiran-Yuan** [comment]
Thank you very much!
